### ISSUE TITLE
GIT is not updated ?!

### ISSUE THREAD

**Issue by Jaxartes** [ntp-project/ntp-missing-author-attribution#15]
This GIT repository (https://github.com/ntp-project/ntp) has no commits since January, in either the "master" or "stable" branch.  Thus it's missing most of the recent 4.2.8p7 release, and the security fixes contained in it.

Were these lost, or didn't they get mirrored from BK, or what?

**Comment by hstenn** [comment]
On 4/28/16 8:53 PM, Jaxartes wrote:

> This GIT repository (https://github.com/ntp-project/ntp) has no commits since January, in either the "master" or "stable" branch.  Thus it's missing most of the recent 4.2.8p7 release, and the security fixes contained in it.
> 
> Were these lost, or didn't they get mirrored from BK, or what?

Glitch.  Should be up soon.

H

**Comment by Jaxartes** [comment]
It's still showing nothing since January here.

**Comment by hstenn** [comment]
On 5/7/16 5:51 PM, Jaxartes wrote:

> It's still showing nothing since January here.

thanks - I'll be finishing this tonight.

The git repos will be upgraded/rewritten as part of this process,
because the new git sync now has author attribution information, and
that changes _all_ of the commits to the repo.

I'll be leaving the original repos on github, probably with names like:

 master-original
 stable-original

unless you (or anybody else) has a better idea.

H

**Comment by hstenn** [comment]
The original repos will be:

 master-no-authorname
 stable-no-authorname

**Comment by ghost** [comment]
There are still no updated branches. Something is still wrong with git sync?

**Comment by hstenn** [comment]
The sync is working, I'm just trying to be certain that when I push the new branches over there that we've done it in a good way.  Right now it's looking like the updated repos will be pushed in a day or two.

**Comment by tcely** [comment]
Is this still a work in progress?

**Comment by suegraves** [comment]
Hi,

Yes, we have tried to get this working again, and it's complicated. If
there are any Git-knowledgeable folks out there that might be able to
volunteer some time to help us, that would be great.

Thanks

Sue

**Comment by FallenGameR** [comment]
Sue, I'm git-knowledgeable and willing to help. What do you need?

**Comment by hstenn** [comment]
FallenGameR, please send me an email. We're at a conference all week but I might have time to work on this one evening. Otherwise I can do it this Saturday. The issue is getting the rewritten repos uploaded to github.

**Comment by rahul267** [comment]
Count me as well !

**Comment by FallenGameR** [comment]
@hstenn, I've just sent you and Sue the email. Not sure how to get emails from github, I found both yours and Sue's addresses from http://bugs.ntp.org/show_bug.cgi?id=3019 =)

**Comment by KingOfDos** [comment]
At IRC the "NTP project" blames BitBucket. Maybe I should call it BitFucket? Proprietary garbage ware?

**Comment by hstenn** [comment]
@KingOfDos, Nobody at the NTP Project has said anything anywhere about BitBucket.

As soon as I get a little competent help regarding uploading the stable repo to github, this problem will be fixed.  The two folks who have offered help before have gotten busy with other things, and to make things worse, they each said that what the other wanted to do was the wrong fix.

**Comment by bernhardschmidt** [comment]
Any news? Two years later the git repo is still out of date
