### ISSUE TITLE
Issues with socketpair and pipe

### ISSUE THREAD

**Issue by workbbraun** [ntp-project/ntp-missing-author-attribution#18]
Currently, pipe_socketpair() will first try socketpair if HAVE_SOCKETPAIR is defined, and fall back to calling pipe() if that fails, returning which one was used in the is_pipe argument.
The work_fork worker model then does two pipe_socketpair() calls in sequence and requires both be the same (first call can't be sockets while the second call was pipe or vice versa, due to a transient failure of socketpair()).  If this happens, the calling process crashes with an assert in INSIST(was_pipe == is_pipe).  In the socketpair case, the second call is unnecessary because the socket is bidirectional anyway, unlike pipes.

Additionally, if HAVE_SOCKETPAIR is defined, sntp will exit with an error if pipe is ever used.  So even if both fall back to pipe() in the HAVE_SOCKETPAIR case, sntp will bail.  If HAVE_SOCKETPAIR is not defined, sntp will succeed.

What's more, ntpd will set SIOCSPGRP on the fd if SIOCSPGRP is defined, regardless of whether the fd is a socket or pipe, and exit on failure.  SIOCSPGRP is not valid for non-sockets, and will always fail.

**Comment by hstenn** [comment]
Please open a report at http:/bugs.ntp.org for this issue.  Thanks!
