### ISSUE TITLE
autoconf fails

### ISSUE THREAD

**Issue by sovietspaceship2** [ntp-project/ntp-missing-author-attribution#22]
> ntp$ autoconf
> cannot open `sntp/m4/version.m4': No such file or directory

line 3 of configure.in:
> m4_include([sntp/m4/version.m4])

and indeed there's no such file
> test -f sntp/m4/version.m4
returns 1

Also, the build instructions are outdated, as there's no configure.in (which was renamed to configure.ac at some point?)

Am I missing something here?

**Comment by hstenn** [comment]
You mean line 3 of configure.ac, right?

Don't run autoconf, run ./bootstrap if you're checking out from a repo.  That will create sntp/m4/version.m4 for you.

We hope to have the github repo up-to-date soon.
