### ISSUE TITLE
lib/isc/unix/ifiter_ioctl.c:188:8: error: format not a string literal and no format arguments [-Werror=format-security]

### ISSUE THREAD

**Issue by nunojpg** [ntp-project/ntp-missing-author-attribution#24]
If I compile ntp-4.2.8p10 on Ubuntu/Debian without libcap-dev installed, I get this error:

> In file included from ./../lib/isc/unix/interfaceiter.c:165:0:
> ./../lib/isc/unix/ifiter_ioctl.c: In function ‘getbuf4’:
> ./../lib/isc/unix/ifiter_ioctl.c:188:8: error: format not a string literal and no format arguments [-Werror=format-security]
>         "size exceeded"));
>         ^~~~~~~~~~~~~~~
> cc1: some warnings being treated as errors

Maybe config should stop if libcap-dev is not present, or/and this warning/error should be fixed as it can also be a issue on other platforms.

Thanks

**Comment by hstenn** [comment]
This seems to be compiler noise, and not a problem with the code.  Do you disagree?

**Comment by nunojpg** [comment]
This happens when compiled with debuild. Maybe this lib is inheriting a Werror from the build system, as there are many other warning that don't break the build...

**Comment by hstenn** [comment]
On 8/14/2017 4:51 PM, Nuno Goncalves wrote:
> This happens when compiled with debuild. Maybe this lib is inheriting a
> Werror from the build system, as there are many other warning that don't
> break the build...

OK, and the error/warning looks like a false-positive report by the
compiler.

We're trying hard to keep the codebase clean and correct.

We used to add things to "quiet" spurious warnings from some compilers,
and discovered that what makes things better for one compiler makes
things worse for another compiler.  So we're now removing those "hacks"
as we find them.

H

**Comment by nunojpg** [comment]
Agree with that.

Still I think there is a bug - this unit fails because it is being compiled with werror. That is probably because "werror" is propagating to this unit, and not others. That inconsistency is a bug.

I'll try to run it again in 2 days and get back with more details. For now it's on hold, and I am closing it.

Thanks!
