### ISSUE TITLE
Questions about intersection algorithm

### ISSUE THREAD

**Issue by slfmessi** [ntp-project/ntp-missing-author-attribution#3]
I am using ntp-4.2.4p7 on a linux host and ntp-4.2.5p172 on a solaris host, which have two same timer. However， I found that aftering give the two timer different time diff about 10s, ntp-4.2.4p7 will activate intersection algorithm while ntp-4.2.5p172 not. I want to know whether there are something different of intersection algorithm between the two versions, because I can't find anything about this on the Internet. For further infomation, is there any method to adjust or simply close intersection algorithm?
Thanks a lot.

**Comment by hstenn** [comment]
The best reference is the book by Dave Mills.

The more important question is why would you want to be looking at software that is so old?

Please see https://support.ntp.org/bin/view/Dev/ReleaseTimeline
